In [2]:
import numpy as np

In [187]:
a=np.arange(1,30,3)
a

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28])

arange(start,stop,step,dtype)


In [188]:
b=np.arange(1,30,3).reshape(5,2)
b

array([[ 1,  4],
       [ 7, 10],
       [13, 16],
       [19, 22],
       [25, 28]])

reshape(rows,cols)/reshape(dimension1,dimension2,....)

In [189]:
apple=np.arange(60).reshape(3,5,2,2)
apple


array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]],

        [[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]],

        [[16, 17],
         [18, 19]]],


       [[[20, 21],
         [22, 23]],

        [[24, 25],
         [26, 27]],

        [[28, 29],
         [30, 31]],

        [[32, 33],
         [34, 35]],

        [[36, 37],
         [38, 39]]],


       [[[40, 41],
         [42, 43]],

        [[44, 45],
         [46, 47]],

        [[48, 49],
         [50, 51]],

        [[52, 53],
         [54, 55]],

        [[56, 57],
         [58, 59]]]])

In [190]:
apple.ndim

4

ndim shows the number of dimensions

In [191]:
?np.arange

?can used instead of help

In [192]:
!dir "c:/"

 Volume in drive C is OSDisk
 Volume Serial Number is C0EC-7A44

 Directory of c:\

11/28/2018  03:22 PM               531 build.ini
11/28/2018  03:20 PM             2,768 DFSInfo.txt
09/24/2019  11:43 AM            16,384 f21127e0d86f553a8baadc4fe3915296.jfm
06/26/2019  09:53 AM    <DIR>          Intel
12/14/2017  07:11 AM    <DIR>          PerfLogs
06/08/2020  01:23 PM    <DIR>          Program Files
06/08/2020  01:19 PM    <DIR>          Program Files (x86)
02/02/2018  06:25 AM    <DIR>          Quarantine
08/30/2019  11:08 AM    <DIR>          Scripts
06/12/2019  01:15 PM    <DIR>          Sun
07/08/2019  12:52 PM    <DIR>          symbols
06/14/2020  10:22 AM    <DIR>          temp
06/09/2020  10:15 PM    <DIR>          Users
06/12/2020  10:26 AM    <DIR>          Windows
11/28/2018  03:57 PM             4,715 wpm_log.txt
               4 File(s)         24,398 bytes
              11 Dir(s)  28,780,158,976 bytes free


can also install by using !pip install pandas

In [193]:
apple.shape

(3, 5, 2, 2)

shape find the shape th n dimensional array and each value is a dimension 

In [194]:
a.dtype

dtype('int32')

dtype our obj created

In [195]:
apple.itemsize

4

itemsize is byte size value

In [196]:
b=np.array([[4,5],[3,5]])

In [197]:
b

array([[4, 5],
       [3, 5]])

array function can assign value from user side

In [198]:
d=np.array([[4,5],[3,5]],dtype=np.int16)

In [199]:
d.dtype

dtype('int16')

In [200]:
c=np.array([3,8.9,9,0])
c

array([3. , 8.9, 9. , 0. ])

numpy array is homogenous all elements will assigned datatype that is the higher order

In [201]:
d.ndim

2

In [202]:
d=np.array([[[[4,5,6],[75,89,20],[2.5,7.8,9.0]]]])
d

array([[[[ 4. ,  5. ,  6. ],
         [75. , 89. , 20. ],
         [ 2.5,  7.8,  9. ]]]])

In [203]:
d.itemsize

8

In [204]:
d.size

9

size shows the total size 

In [205]:
d=np.array([[[[4,5,6],[75,89,20],[2.5,7.8,9.0]]]])

In [206]:
d

array([[[[ 4. ,  5. ,  6. ],
         [75. , 89. , 20. ],
         [ 2.5,  7.8,  9. ]]]])

In [207]:
x=[[[[4,5,6],[75,89,20],[2.5,7.8,9.0]]]]

In [208]:
x

[[[[4, 5, 6], [75, 89, 20], [2.5, 7.8, 9.0]]]]

In [209]:
z=np.array([[[[4,5,6],[75,89,20],[2.5,7.8,9.0]][1,2,5]]])

TypeError: list indices must be integers or slices, not tuple

In [ ]:
b=np.array(([(1,2,3),(3,4,5)],[(8,9,10),(11,12,13)],[(8,7,10),(2,5,7)]))

In [ ]:
b

In [ ]:
f=np.array([[1,2],[3,4]],dtype=complex)
f

complex number generation

In [ ]:
zer=np.zeros((5,10))#every value is zero
zer

np.zeros((dimension1,dimension2,dimension3....))

In [ ]:
onez=np.ones((2,3,6))#every value is one

In [ ]:
onez

In [ ]:
zer1=np.empty((5,3,2))#every value is some small value
zer1

In [ ]:
fert=np.arange(1,2,0.1)
fert

steps can also be floating number

In [ ]:
fert1=np.linspace(1,2,13)
fert1

linspace= (start ,stop, number of values needed and stop!=stop-1 all values are taken in above eg:2 is stop it is also include)

In [ ]:
fert2=np.logspace(1,2,3)
fert2

value  10^x, 10^anyvaluebetween (x and y) 10^y

In [ ]:
a12=np.arange(48).reshape(2,6,4)
a12

In [ ]:
a12[1,2:4,1:3]

In [ ]:
a12[1,2:4,-2:-4:-1]

In [ ]:
np.set_printoptions(threshold=np.inf)
axe=np.arange(10000).reshape(100,100)
axe

threshold only for printing purpose threshold= value upto that value we show otherwise it will summarized

In [ ]:
a12[::-1,:,:]

In [ ]:
a12[:,::-1,:]

In [ ]:
a12

In [ ]:
a12[0,1,1]

In [ ]:
a12[0,-1,1]

In [ ]:
a12[-1,-1,-1]

In [ ]:
a12[1,:,2]

In [ ]:
a12[1,1,:]

In [ ]:
yz=np.arange(10,40).reshape(2,3,5)
yz2=np.arange(15,45).reshape(2,3,5)
print(" A= {0} \n-----------------------------\n B= {1}".format(yz,yz2))

In [ ]:
c=yz+yz2
c

In [ ]:
c=yz-yz2
c

In [ ]:
yz2=np.arange(15,45).reshape(2,3,5)


In [ ]:
c=yz-yz2

In [ ]:
c

In [ ]:
yz=np.arange(10,40).reshape(2,3,5)

In [ ]:
c=yz-yz2

In [ ]:
c

In [ ]:
yz*10

In [ ]:
yz/2

In [ ]:
yz**3

In [ ]:
yz>14

In [ ]:
yz**yz2

## 

In [ ]:
yz2

In [ ]:
yz

In [ ]:
yz*yz2

yz*yz2 only gives element by elemnt multiplication

In [ ]:
yz

In [ ]:
yz2

In [ ]:
yz**yz2

In [ ]:
yz**(2*np.ones((2,3,5)))

In [ ]:
yz

In [ ]:
yz2

In [ ]:
np.int32(10**15)#Issue with c type casting to python bug

In [ ]:
np.__version__

In [ ]:
a=np.array([[2,2],[2,2]])
b=np.array([[4,4],[4,4]])

In [ ]:
a

In [ ]:
b

In [ ]:
a.dot(b)

In [ ]:
np.dot(a,b)

for normal matrix multiplication we should use eg: a.dot(b) or np.dot(a,b)

In [ ]:
a+=2

In [ ]:
a

In [ ]:
u=np.random.random((2,2))

In [ ]:
u

In [ ]:
u+=a#possible
u

In [ ]:
a+=u#not possible bigger to low conversion is not allowed
a

compi=np.exp(c*2j)

In [ ]:
compi=np.exp(c*2j)

In [ ]:
compi

UNARY FUNCTIONS

In [ ]:
compi.sum()#sum of all values

In [ ]:
compi.min()

In [ ]:
compi.max()

In [ ]:
compi.argmax()# index is i given serially

In [ ]:
compi.argmin()# index is i given serially

In [ ]:
aplle12=np.arange(20).reshape(2,2,5)
aplle12

In [ ]:
aplle12.argmin(0)

In [ ]:
aplle12.argmin(2)

In [ ]:
aplle12.argmin(1)

UFUNC or Universal function

arange,exp,sqrt,add

In [ ]:
np.exp(aplle12)# create exponential values based on the array specified

In [ ]:
a

In [ ]:
b=np.array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28])

In [ ]:
np.add(a,b)

In [ ]:
np.subtract(b,np.add(a,b))

In [ ]:
ruby=np.empty((10))

In [ ]:
np.subtract(b,np.add(a,b), out=ruby)# same as = operator but = operator is dangerus it is not copying it is creating a subset of it

In [ ]:
ruby[:4:2]

In [ ]:
ruby[1]

In [ ]:
def f(x,y):
    return 10*x+y
cfrm=np.fromfunction(f,(5,4),dtype=int)
cfrm

In [ ]:
def c(x,y,z):#x ,y ,z aredimensions
    return (x+7)
calen=np.fromfunction(c,(12,5,7),dtype=int)
calen
        
        
        

In [ ]:
zilu=np.random.random((3,5,2))
zilu

In [ ]:
zilu.argmin(0)

In [ ]:
zilu.argmin(1)

In [ ]:
zilu.argmin(2)

In [ ]:
calen[:,:,-1]

In [ ]:
calen[-1,:,-1]

In [ ]:
calen.ravel()#flatten the array to single dimension

In [ ]:
zilu

In [ ]:
zilu.reshape(6,5, order ="C")# C style lowest dimension is  filled faster here  row(5)

In [ ]:
zilu.reshape(6,5, order ="F")# Fortran style highest dimension is  filled faster here col(6)

In [ ]:
np.ceil(zilu)#opposite is floor

In [ ]:
exper=np.arange(40).reshape(2,2,2,5)
exper

In [ ]:
np.sum(exper, axis=0)

In [ ]:
np.sum(exper,axis=1)

In [ ]:
np.sum(exper,axis=1).shape

In [ ]:
np.sum(exper, axis=0).shape

In [210]:
np.sum(exper,axis=2)

array([[[ 5,  7,  9, 11, 13],
        [25, 27, 29, 31, 33]],

       [[45, 47, 49, 51, 53],
        [65, 67, 69, 71, 73]]])

In [211]:
np.exp(exper)

array([[[[1.00000000e+00, 2.71828183e+00, 7.38905610e+00,
          2.00855369e+01, 5.45981500e+01],
         [1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
          2.98095799e+03, 8.10308393e+03]],

        [[2.20264658e+04, 5.98741417e+04, 1.62754791e+05,
          4.42413392e+05, 1.20260428e+06],
         [3.26901737e+06, 8.88611052e+06, 2.41549528e+07,
          6.56599691e+07, 1.78482301e+08]]],


       [[[4.85165195e+08, 1.31881573e+09, 3.58491285e+09,
          9.74480345e+09, 2.64891221e+10],
         [7.20048993e+10, 1.95729609e+11, 5.32048241e+11,
          1.44625706e+12, 3.93133430e+12]],

        [[1.06864746e+13, 2.90488497e+13, 7.89629602e+13,
          2.14643580e+14, 5.83461743e+14],
         [1.58601345e+15, 4.31123155e+15, 1.17191424e+16,
          3.18559318e+16, 8.65934004e+16]]]])

In [216]:
a=np.arange(-1004,-1000)
for i in a:
    print(i**1/3.)

-334.6666666666667
-334.3333333333333
-334.0
-333.6666666666667


In [217]:
exper.T

array([[[[ 0, 20],
         [10, 30]],

        [[ 5, 25],
         [15, 35]]],


       [[[ 1, 21],
         [11, 31]],

        [[ 6, 26],
         [16, 36]]],


       [[[ 2, 22],
         [12, 32]],

        [[ 7, 27],
         [17, 37]]],


       [[[ 3, 23],
         [13, 33]],

        [[ 8, 28],
         [18, 38]]],


       [[[ 4, 24],
         [14, 34]],

        [[ 9, 29],
         [19, 39]]]])

In [218]:
exper

array([[[[ 0,  1,  2,  3,  4],
         [ 5,  6,  7,  8,  9]],

        [[10, 11, 12, 13, 14],
         [15, 16, 17, 18, 19]]],


       [[[20, 21, 22, 23, 24],
         [25, 26, 27, 28, 29]],

        [[30, 31, 32, 33, 34],
         [35, 36, 37, 38, 39]]]])

In [219]:
exper.T.shape# just flips the shape

(5, 2, 2, 2)

In [220]:
exper.shape

(2, 2, 2, 5)

In [221]:
exper

array([[[[ 0,  1,  2,  3,  4],
         [ 5,  6,  7,  8,  9]],

        [[10, 11, 12, 13, 14],
         [15, 16, 17, 18, 19]]],


       [[[20, 21, 22, 23, 24],
         [25, 26, 27, 28, 29]],

        [[30, 31, 32, 33, 34],
         [35, 36, 37, 38, 39]]]])

In [224]:
np.hsplit(exper,2)

[array([[[[ 0,  1,  2,  3,  4],
          [ 5,  6,  7,  8,  9]]],
 
 
        [[[20, 21, 22, 23, 24],
          [25, 26, 27, 28, 29]]]]),
 array([[[[10, 11, 12, 13, 14],
          [15, 16, 17, 18, 19]]],
 
 
        [[[30, 31, 32, 33, 34],
          [35, 36, 37, 38, 39]]]])]

In [233]:
np.hsplit()

In [230]:
arr23=np.arange(12).reshape(2,6)
arr23

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [234]:
np.hsplit(arr23,(3))

[array([[0, 1],
        [6, 7]]),
 array([[2, 3],
        [8, 9]]),
 array([[ 4,  5],
        [10, 11]])]

In [235]:
np.hsplit(arr23,(3,4))

[array([[0, 1, 2],
        [6, 7, 8]]),
 array([[3],
        [9]]),
 array([[ 4,  5],
        [10, 11]])]

In [236]:
np.hsplit(arr23,(3,4,5))

[array([[0, 1, 2],
        [6, 7, 8]]),
 array([[3],
        [9]]),
 array([[ 4],
        [10]]),
 array([[ 5],
        [11]])]

In [243]:
np.vsplit(arr23,(1,2))

[array([[0, 1, 2, 3, 4, 5]]),
 array([[ 6,  7,  8,  9, 10, 11]]),
 array([], shape=(0, 6), dtype=int32)]

In [241]:
arr23

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [244]:
yup=np.hsplit(arr23,(3,4,5))
yup

In [286]:
arr231=np.arange(20).reshape(5,4)
arr231

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [252]:
np.vsplit(arr231,(1,2))

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])]

In [257]:
np.vstack(arr231)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [255]:
np.hstack(arr231)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [259]:
arr12=arr231

In [260]:
arr12 is arr231

True

In [265]:
arr12[2,2]=3
arr12

array([[ 0,  1,  2,  3],
       [ 3,  3,  3,  3],
       [ 8,  9,  3, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [266]:
arr231

array([[ 0,  1,  2,  3],
       [ 3,  3,  3,  3],
       [ 8,  9,  3, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [287]:
f=arr231.view()# creates view of arr231
f is arr231

False

In [281]:
f

array([[ 0,  1,  2,  3],
       [ 3,  3,  3,  3],
       [ 8,  9,  3, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [282]:
f.shape

(5, 4)

In [283]:
arr231.shape

(5, 4)

In [288]:
f.base is arr231

False

In [289]:
xyz=arr231.view()
xyz.base is arr231

False

In [1]:
import numpy as np
arr234=np.arange(12).reshape(2,3,2)
xyz=arr234.view()
xyz.base is arr234

False

In [2]:
#The is creating false result only because reshape function is actully creating a view and there by arr234 also own data
arr234.flags.owndata#even arr234 is mapped to something else

False

In [1]:
#resolution is make a explicit copy
import numpy as np
arty=np.arange(12).reshape(2,3,2).copy()# creates an explicit copy 
xy=arty.view()
xy.base is arty

True

In [2]:
np.reshape?

In [3]:
arty6=np.arange(20).reshape((5,4)).copy()
x=arty6.view()
x.base is arty6

True

In [4]:
lob=np.array(np.arange(24).reshape(2,3,2,2),dtype='int32')
lob

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]],

        [[ 8,  9],
         [10, 11]]],


       [[[12, 13],
         [14, 15]],

        [[16, 17],
         [18, 19]],

        [[20, 21],
         [22, 23]]]])

In [5]:
lob.astype(int)

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]],

        [[ 8,  9],
         [10, 11]]],


       [[[12, 13],
         [14, 15]],

        [[16, 17],
         [18, 19]],

        [[20, 21],
         [22, 23]]]])

In [6]:
sumres=np.empty((8)).reshape(2,2,2)
np.sum(lob,axis=3).shape

(2, 3, 2)

In [7]:
lob

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]],

        [[ 8,  9],
         [10, 11]]],


       [[[12, 13],
         [14, 15]],

        [[16, 17],
         [18, 19]],

        [[20, 21],
         [22, 23]]]])

In [8]:
lob.argmin(axis=0)

array([[[0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0]]], dtype=int64)

In [9]:
sp=np.random.random((2,3,2,2))*23
sp=np.array(sp,dtype="int32")
sp

array([[[[ 9,  2],
         [19, 11]],

        [[21, 16],
         [17,  3]],

        [[11, 16],
         [ 5, 18]]],


       [[[ 6,  7],
         [13, 22]],

        [[ 3,  7],
         [ 7,  8]],

        [[11,  0],
         [12,  3]]]])

In [10]:
sp.argmin()

21

In [11]:
np.ndenumerate(sp)
sp

array([[[[ 9,  2],
         [19, 11]],

        [[21, 16],
         [17,  3]],

        [[11, 16],
         [ 5, 18]]],


       [[[ 6,  7],
         [13, 22]],

        [[ 3,  7],
         [ 7,  8]],

        [[11,  0],
         [12,  3]]]])

In [12]:
sp
    

array([[[[ 9,  2],
         [19, 11]],

        [[21, 16],
         [17,  3]],

        [[11, 16],
         [ 5, 18]]],


       [[[ 6,  7],
         [13, 22]],

        [[ 3,  7],
         [ 7,  8]],

        [[11,  0],
         [12,  3]]]])

In [13]:
test=np.random.randint(0,10,(4,3)).copy()
test

array([[7, 7, 2],
       [1, 9, 6],
       [4, 6, 7],
       [8, 7, 4]])

In [14]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
for x in arr:
    for y in arr:
        for z in arr:
            print(arr)
            

    

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [39]:
test2=test.copy()*21
for i,j in zip(test,test2):
    print(i,'+',j,'=',i**(1/3*j))

[7 7 2] + [147 147  42] = [2.56923578e+41 2.56923578e+41 1.63840000e+04]
[1 9 6] + [ 21 189 126] = [1.00000000e+00 1.31002051e+60 4.81229803e+32]
[4 6 7] + [ 84 126 147] = [7.20575940e+16 4.81229803e+32 2.56923578e+41]
[8 7 4] + [168 147  84] = [3.74144419e+50 2.56923578e+41 7.20575940e+16]


In [61]:
sp

array([[[[ 9,  2],
         [19, 11]],

        [[21, 16],
         [17,  3]],

        [[11, 16],
         [ 5, 18]]],


       [[[ 6,  7],
         [13, 22]],

        [[ 3,  7],
         [ 7,  8]],

        [[11,  0],
         [12,  3]]]])

In [65]:
sp.repeat(2,3)

array([[[[ 9,  9,  2,  2],
         [19, 19, 11, 11]],

        [[21, 21, 16, 16],
         [17, 17,  3,  3]],

        [[11, 11, 16, 16],
         [ 5,  5, 18, 18]]],


       [[[ 6,  6,  7,  7],
         [13, 13, 22, 22]],

        [[ 3,  3,  7,  7],
         [ 7,  7,  8,  8]],

        [[11, 11,  0,  0],
         [12, 12,  3,  3]]]])

In [82]:
np.logspace(1,6,4,True,2,'int16')



array([ 2,  6, 20, 64], dtype=int16)

In [83]:
sp[sp>3]#creates a single dimensional array with elemnts having value greater than 3

array([ 9, 19, 11, 21, 16, 17, 11, 16,  5, 18,  6,  7, 13, 22,  7,  7,  8,
       11, 12])

array([[[[119,  40],
         [380, 159]],

        [[713, 384],
         [408, 281]],

        [[201, 464],
         [145, 404]]],


       [[[127, 196],
         [364, 575]],

        [[ 58,  77],
         [ 77, 113]],

        [[121,   0],
         [168,   9]]]])

In [96]:


d = np.exp(sp)
d

array([[[[8.10308393e+03, 7.38905610e+00],
         [1.78482301e+08, 5.98741417e+04]],

        [[1.31881573e+09, 8.88611052e+06],
         [2.41549528e+07, 2.00855369e+01]],

        [[5.98741417e+04, 8.88611052e+06],
         [1.48413159e+02, 6.56599691e+07]]],


       [[[4.03428793e+02, 1.09663316e+03],
         [4.42413392e+05, 3.58491285e+09]],

        [[2.00855369e+01, 1.09663316e+03],
         [1.09663316e+03, 2.98095799e+03]],

        [[5.98741417e+04, 1.00000000e+00],
         [1.62754791e+05, 2.00855369e+01]]]])

In [19]:
import numpy as np
def f(z,y,x):
    calen=y*7+x+1
    
    calen[0,4,3:]=0
    calen[1,4,:]=0
    calen[2::2,4,3:]=calen[2::2,4,3:]-np.array([32,33,34,35])
    calen[3::2,4,2:]=calen[3::2,4,2:]-np.array([31,32,33,34,35])
    return calen
sp=np.fromfunction(f,(12,5,7),dtype=int)
sp

array([[[ 1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19, 20, 21],
        [22, 23, 24, 25, 26, 27, 28],
        [29, 30, 31,  0,  0,  0,  0]],

       [[ 1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19, 20, 21],
        [22, 23, 24, 25, 26, 27, 28],
        [ 0,  0,  0,  0,  0,  0,  0]],

       [[ 1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19, 20, 21],
        [22, 23, 24, 25, 26, 27, 28],
        [29, 30, 31,  0,  0,  0,  0]],

       [[ 1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19, 20, 21],
        [22, 23, 24, 25, 26, 27, 28],
        [29, 30,  0,  0,  0,  0,  0]],

       [[ 1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19, 20, 21],
        [22, 23, 24, 25, 26, 27, 28],
        [29, 30, 31,  0,  0,  0,  0]],

       [[ 1,  2,  3,  4,  5,  6,  7],
  

In [25]:
?np.fromfunction

In [26]:
np.ravel?

In [27]:
exper=np.arange(40).reshape(2,2,2,5)
exper

array([[[[ 0,  1,  2,  3,  4],
         [ 5,  6,  7,  8,  9]],

        [[10, 11, 12, 13, 14],
         [15, 16, 17, 18, 19]]],


       [[[20, 21, 22, 23, 24],
         [25, 26, 27, 28, 29]],

        [[30, 31, 32, 33, 34],
         [35, 36, 37, 38, 39]]]])

In [36]:
np.vsplit(exper,2)

[array([[[[ 0,  1,  2,  3,  4],
          [ 5,  6,  7,  8,  9]],
 
         [[10, 11, 12, 13, 14],
          [15, 16, 17, 18, 19]]]]),
 array([[[[20, 21, 22, 23, 24],
          [25, 26, 27, 28, 29]],
 
         [[30, 31, 32, 33, 34],
          [35, 36, 37, 38, 39]]]])]

In [40]:
arr23=np.arange(12).reshape(6,2)
arr23

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [59]:
np.vsplit?